### ISSUE TITLE
Product Manager Login Error.

### ISSUE THREAD

**Issue by RichardTumba** [Kaushallrai/Inventory-System#11]
I tried to login using the product manager's id. It game me a error saying:

![error](https://github.com/Kaushallrai/Inventory-System/assets/127919833/b3054c50-d981-44b3-90fb-73b56d040799)

**Comment by ghost** [comment]
The reasoning behind the issue was that the product manager was being confused with admin but product manager is not allowed to access the admin dashboard. It is now fixed.
